name = "polyxor"
defaultTargets = ["PolyXOR"]
enableArtifactCache = true

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"

[[lean_lib]]
name = "PolyXOR"
roots = ["PolyXORCheck"]
globs = ["PolyXORCompress", "PolyXORFull", "PolyXORCheck", "PolyXOR.+"]
